config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "forecasts#new"

  resource :forecasts, only: %i[new show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def new
  end

  def show
    errors = []

    @zip_code = params[:zip_code]
    @country_code = params[:country_code]

    errors << 'Address must have a zip code' if @zip_code.blank?
    errors << 'Address must have a country code' if @country_code.blank?
    if errors.any?
      flash[:alert] = errors.join(', ')
      redirect_to new_forecasts_path
      return
    end

    @data = WeatherProxy.get_weather_data(zip_code: @zip_code, country_code: @country_code)
  rescue StandardError => e
    flash[:alert] = 'Unable to fetch weather data. Please try again later.'
    redirect_to new_forecasts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecasts/new.html.erb
<section class="vh-100" style="background-size: 100% 100%; background-image: url('https://images.unsplash.com/photo-1592210454359-9043f067919b?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">

        <div class="card shadow-0 border border-dark border-5 text-dark" style="border-radius: 10px; padding: 4rem;">
          <div class="card-body p-4">
            <h1 class="text-center">Weather Forecaster</h1>
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <p><%= flash[:alert] %></p>
                <%= form_with(model: @forecast, url: forecasts_path, method: :get) do |form| %>
                  <div class="input-group">
                    <input id="autocomplete" type="search" placeholder="Enter a location" class="form-control" />
                    <input type="hidden" name="country_code" id="country_code" />
                    <input type="hidden" name="zip_code" id="zip_code" />
                    <%= form.submit "Show Forecast", class: 'btn btn-primary' %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_PLACES_API_KEY']}&loading=async&libraries=places&callback=initMap" %>

<script>
  let autocomplete;

  function initMap() {
    const input = document.getElementById("autocomplete");
    autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.addListener("place_changed", function() {
      const place = autocomplete.getPlace();

      if (place && place.address_components) {
        for (const component of place.address_components) {
          const componentType = component.types[0];

          switch(componentType) {
            case "country":
              document.getElementById("country_code").value = component.short_name;
              break;
            case "postal_code":
              document.getElementById("zip_code").value = component.short_name;
              break;
          }
        }
      }
    });
  }
</script>

app/views/forecasts/show.html.erb
<section class="vh-100" style="background-size: 100% 100%; background-image: url('https://images.unsplash.com/photo-1592210454359-9043f067919b?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
  <%= link_to "New Search", root_path, class: "btn btn-primary", style: "position: absolute; left: 1rem; top: 1rem;" %>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-10">
        <div class="card shadow-0 border border-dark border-5 text-dark" style="border-radius: 10px;">
          <div class="card-body p-4">
            <div class="row text-center">
              <div class="d-flex justify-content-around mt-3">
                <p class="small"><strong>Country</strong>: <%= @country_code %></p>
                <p class="small"><strong>Postal Code</strong>: <%= @zip_code %></p>
                <p class="small"><strong>Lat, Lon</strong>: <%= @data[:lat] %>, <%= @data[:lon] %></p>
                <p class="small text-center">
                  <% if @data[:cache_exists] %><i>Data retrieved from cache</i><% end %>
                </p>
              </div>
              <div class="d-flex justify-content-around align-items-center py-5 my-4">
                <p class="fw-bold mb-0" style="font-size: 7rem;"><%= @data[:temp] %>°F</p>
                <div class="text-center">
                  <p class="h3 mb-2"><%= @data[:day_of_week] %></p>
                  <p class="small mb-0"><%= @data[:date] %></p>
                  <p class="small"><%= @data[:time] %></p>
                </div>
              </div>
              <div class="d-flex justify-content-around align-items-center mb-3">
                <div class="flex-column">
                  <p class="small mb-1">Forecast</p>
                  <p class="small mb-0"><strong>High</strong></p>
                  <p class="small mb-0"><strong>Low</strong></p>
                </div>
                <% @data[:daily].each do |day| %>
                  <div class="flex-column">
                    <p class="small mb-1"><%= day[:day_of_week] %></p>
                    <p class="small mb-0"><strong><%= day[:temp_max] %>°F</strong></p>
                    <p class="small mb-0"><strong><%= day[:temp_min] %>°F</strong></p>
                  </div>
                <% end %>
                <div class="flex-column">
                  <i class="fas fa-minus"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>